---

- name: Ensure required packages are installed
  become: true
  loop: "{{ debian_dependencies }}"
  when: item not in ansible_facts.packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true

- name: Download Microsoft GPG key and dearmor it
  become: true
  ansible.builtin.get_url:
    url: https://packages.microsoft.com/keys/microsoft.asc
    dest: /tmp/microsoft.asc
    mode: '0644'

- name: Dearmor Microsoft GPG key
  become: true
  ansible.builtin.command:
    cmd: >
      gpg --dearmor -o /usr/share/keyrings/microsoft.gpg /tmp/microsoft.asc
  args:
    creates: /usr/share/keyrings/microsoft.gpg

- name: Set permissions on dearmored key
  become: true
  ansible.builtin.file:
    path: /usr/share/keyrings/microsoft.gpg
    owner: root
    group: root
    mode: '0644'

# TODO pull from here https://packages.microsoft.com/config/ubuntu/22.04/
- name: Ensure VS Code APT repository is present
  become: true
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/vscode.sources
    content: |
      ### THIS FILE IS AUTOMATICALLY CONFIGURED ###
      # You may comment out this entry, but any other modifications may be lost.
      Types: deb
      URIs: https://packages.microsoft.com/repos/code
      Suites: stable
      Components: main
      Architectures: amd64
      Signed-By: /usr/share/keyrings/microsoft.gpg
    owner: root
    group: root
    mode: '0644'
  diff: true

...
